# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       time
Summary:    A GNU utility for monitoring a program's use of system resources
Version:    1.7
Release:    33
Group:      Applications/System
License:    GPLv2+
URL:        http://www.gnu.org/software/time/
Source0:    ftp://prep.ai.mit.edu/pub/gnu/%{name}/%{name}-%{version}.tar.gz
Source100:  time.yaml
Patch0:     time-1.7-destdir.patch
Patch1:     time-1.7-verbose.patch
Patch2:     fix-info-direntry.patch
BuildRequires:  texinfo


%description
The GNU time utility runs another program, collects information about
the resources used by that program while it is running, and displays
the results.



%package docs
Summary:    Documentation files for %{name}
Group:      Applications/System
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/install-info
Requires(postun): /sbin/install-info

%description docs
%{summary}.



%prep
%setup -q -n %{name}-%{version}

# time-1.7-destdir.patch
%patch0 -p1
# time-1.7-verbose.patch
%patch1 -p1
# fix-info-direntry.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
echo "ac_cv_func_wait3=\${ac_cv_func_wait3='yes'}" >> config.cache
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post







%post docs
%install_info --info-dir=%_infodir %{_infodir}/time.info.gz

%postun docs
if [ $1 = 0 ] ;then
%install_info_delete --info-dir=%{_infodir} %{_infodir}/time.info.gz
fi

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_bindir}/time
# << files


%files docs
%defattr(-,root,root,-)
# >> files docs
%doc NEWS README COPYING
%doc %{_infodir}/time.info.gz
# << files docs

